name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: |
          .next
          public
          package.json
          
  # Раскомментируйте этот блок, когда будете готовы к автоматическому деплою
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   
  #   steps:
  #   - name: Download build artifacts
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: build-files
  #       
  #   - name: Deploy to production
  #     # Здесь используйте действие для деплоя на ваш сервер
  #     # Например, для деплоя на сервер через SSH:
  #     run: |
  #       echo "Deploying to production server..."
  #       # Команды для деплоя на ваш сервер 