name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Build
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"
      run: pnpm run build
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: |
          .next
          public
          package.json
          
  # Раскомментируйте этот блок, когда будете готовы к автоматическому деплою
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   
  #   steps:
  #   - name: Download build artifacts
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: build-files
  #       
  #   - name: Deploy to production
  #     # Здесь используйте действие для деплоя на ваш сервер
  #     # Например, для деплоя на сервер через SSH:
  #     run: |
  #       echo "Deploying to production server..."
  #       # Команды для деплоя на ваш сервер 